language: go

sudo: false

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get github.com/DataDog/datadog-go/statsd
  - go get github.com/gorilla/handlers
  - go get github.com/stretchr/testify/assert

script:
  - go test -v ./...
